GET http://localhost:3000/api/trabajos/finalizados/contratados/32fc1807-6d11-42dd-bdd9-3dd5e82147e0

### Obtener una provincia (Con el id o cualquier otro atributo de la class)
GET http://localhost:3000/api/trabajos

### Crear una nueva provincia (POST - crear recurso)
# @name createTrabajo
POST http://localhost:3000/api/trabajos
Content-Type: application/json

{ 
  "montoTotal": 1000,
  "cliente": "32fc1807-6d11-42dd-bdd9-3dd5e82147e0",
  "profesional": "8bfc359b-40cc-4a49-924a-8182a98710ba",
  "fechaSolicitud": "08/11/2025"
}

### Modifica una provincia (PUT - modificar recurso completo e idempotente)
@id = {{createTrabajo.response.body.data.id}}
PUT http://localhost:3000/api/trabajos/1
Content-Type: application/json

{ 
  "fechaPago": "30/10/2025",
  "fechaFinalizado": "29/10/2025"
}

### Modificar una provincia (PATCH - modificar recurso parcialmente)
PATCH http://localhost:3000/api/trabajos/1
Content-Type: application/json

{ 
  "fechaPago": "30/10/2025",
  "fechaFinalizado": "29/10/2025",
  "resenia": 4
}

### Eliminar una provicia (DELETE - eliminar recurso)
DELETE http://localhost:3000/api/trabajos/3

/* La extension REST Client, nos permite hacer peticiones sin la 
la necesidad del navegador, por ejemplo meter un archivo reversionado
dentro del proyecto y realizarle peticiones y controlar que funcione
todo correctamente */