GET http://localhost:3000/api/trabajos

### Obtener una provincia (Con el id o cualquier otro atributo de la class)
GET http://localhost:3000/api/trabajos/{{id}}

### Crear una nueva provincia (POST - crear recurso)
# @name createTrabajo
POST http://localhost:3000/api/trabajos
Content-Type: application/json

{ 
  "montoTotal": 1500,
  "cliente": "e7c98f61-ab75-4aaa-a66c-1a5cfeb8ae09",
  "profesional": "5495f33f-d888-426c-bdf4-2ebd7bcf6dea",
  "fechaSolicitud": "20/10/2025"
}

### Modifica una provincia (PUT - modificar recurso completo e idempotente)
@id = {{createTrabajo.response.body.data.id}}
PUT http://localhost:3000/api/trabajos/{{id}}
Content-Type: application/json

{ 
  
}

### Modificar una provincia (PATCH - modificar recurso parcialmente)
PATCH http://localhost:3000/api/provincia/{{id}}
Content-Type: application/json

{ 
}

### Eliminar una provicia (DELETE - eliminar recurso)
DELETE http://localhost:3000/api/provincia/{{id}}


/* La extension REST Client, nos permite hacer peticiones sin la 
la necesidad del navegador, por ejemplo meter un archivo reversionado
dentro del proyecto y realizarle peticiones y controlar que funcione
todo correctamente */