### GET ALL INACTIVE
GET http://localhost:3000/api/profesion/inactive

### GET ALL ACTIVE
GET http://localhost:3000/api/profesion

### POST
# @name createProfesion
POST http://localhost:3000/api/profesion
Content-Type: application/json

{ 
  "nombreProfesion": "Albañil",
  "descripcionProfesion": "Amazame esta",
  "estado": true
}

### ID
@id = {{createProfesion.response.body.data.nombreProfesion}}
### GET ONE
GET http://localhost:3000/api/profesion/{{id}}


### PUT
PUT http://localhost:3000/api/profesion/Ingeniero%20en%20sistemas
Content-Type: application/json

{ 
  "nombreProfesion": "Ingeniero en sistemas",
  "descripcionProfesion": "...",
  "estado": true
}


### PATCH
PATCH http://localhost:3000/api/profesion/{{id}}
Content-Type: application/json

{ 
  "estado": true
}

### Eliminar una profesion (DELETE - eliminar recurso)
DELETE http://localhost:3000/api/profesion/"ingenieria en sistemas"

