### GET ALL ACTIVE
GET http://localhost:3000/api/profesion

### GET ALL INACTIVE
GET http://localhost:3000/api/profesion/inactive

### GET ONE ACTIVE
@id = {{createProfesion.response.body.data.id}}
GET http://localhost:3000/api/profesion/{{id}}

### POST
# @name createProfesion
POST http://localhost:3000/api/profesion
Content-Type: application/json

{ 
  "nombreProfesion": "Plomero",
  "descripcionProfesion": "...",
  "estado": false
}

### PUT
PUT http://localhost:3000/api/profesion/{{id}}
Content-Type: application/json

{ 
  "nombreProfesion": "Ingeniero",
  "descripcionProfesion": "...",
  "estado": true
}

### PATCH
PATCH http://localhost:3000/api/profesion/{{id}}
Content-Type: application/json

{ 
  "nombreProfesion": "Ingeniero",
  "descripcionProfesion": "...",
  "estado": false
}

### DELETE
DELETE http://localhost:3000/api/profesion/{{id}}


/* La extension REST Client, nos permite hacer peticiones sin la 
la necesidad del navegador, por ejemplo meter un archivo reversionado
dentro del proyecto y realizarle peticiones y controlar que funcione
todo correctamente */