### GET ALL INACTIVE
GET http://localhost:3000/api/profesion/inactive

### GET ALL ACTIVE
GET http://localhost:3000/api/profesion

### POST
# @name createProfesion
POST http://localhost:3000/api/profesion
Content-Type: application/json

{ 
  "nombreProfesion": "Ingeniero",
  "descripcionProfesion": "hola",
  "estado": false
}

### ID
@id = {{createProfesion.response.body.data.id}}
### GET ONE
GET http://localhost:3000/api/profesion/{{id}}


### PUT
PUT http://localhost:3000/api/profesion/{{id}}
Content-Type: application/json

{ 
  "nombreProfesion": "Ingeniero",
  "descripcionProfesion": "...",
  "estado": true
}


### PATCH
PATCH http://localhost:3000/api/profesion/{{id}}
Content-Type: application/json

{ 
  "nombreProfesion": "Plomero",
  "descripcionProfesion": "...",
  "estado": true
}

### Eliminar una provicia (DELETE - eliminar recurso)
DELETE http://localhost:3000/api/profesion/{{id}}

