### GET ALL
GET http://localhost:3000/api/post


### POST
# @name createPost
POST http://localhost:3000/api/post/
Content-Type: application/json

{
  "user": "0d406f9e-4fb0-41a2-8faa-324b21e48fa1",
  "texto" : "Este es el septimo posteo que hago"
}

### GET
GET http://localhost:3000/api/post?limit=5
Content-Type: application/json

{
  
}


###
DELETE http://localhost:3000/api/post/b7c2fd80-19a7-4263-8b73-3d456b6789f6
Content-Type: application/json

{
  
}