### GET ALL
GET http://localhost:3000/api/admin


### POST
# @name createAdmin
POST http://localhost:3000/api/admin
Content-Type: application/json

{
  "user": "admin",
  "clave": "1234"
}