### GET ALL
GET http://localhost:3000/api/admin/a73cba1d-2f43-4aeb-bbc4-17b564c31ce0


### POST
# @name createAdmin
POST http://localhost:3000/api/admin/register
Content-Type: application/json

{
  "user": "admin",
  "email" : "augus@gmail.com" ,
  "clave": "1234"
}

###
POST http://localhost:3000/api/admin/register
Content-Type: application/json

{
  "user":"admin",
  "email":"augus@gmail.com",
  "clave":"1234"
}