### GET ALL
GET http://localhost:3000/api/localidad

### GET ONE
GET http://localhost:3000/api/localidad/Cañada%20de%20Gomez

### POST
# @name createLocalidad
POST http://localhost:3000/api/localidad
Content-Type: application/json

{ 
  "nombre": "Rosario",
  "codPostal": "2000",
  "provincia": "Santa Fe"
}

### ID
@id = {{createLocalidad.response.body.data.id}}
### GET ONE
GET http://localhost:3000/api/localidad/{{id}}


### PUT
PUT http://localhost:3000/api/localidad/{{id}}
Content-Type: application/json

{ 
  "nombre": "Canada de Gomez",
  "codPostal": "2500",
  "provincia": 1
}

### PATCH
PATCH http://localhost:3000/api/localidad/{{id}}
Content-Type: application/json

{ 
  "nombre": "Canada de Gomez",
  "codPostal": "2500",
  "provincia": 1
}

### Eliminar una provicia (DELETE - eliminar recurso)
DELETE http://localhost:3000/api/localidad/Rosario


/* La extension REST Client, nos permite hacer peticiones sin la 
la necesidad del navegador, por ejemplo meter un archivo reversionado
dentro del proyecto y realizarle peticiones y controlar que funcione
todo correctamente */