GET http://localhost:3000/api/usuario

### Obtener un usuario (Con el id o cualquier otro atributo de la class)
GET http://localhost:3000/api/usuario/6759802b-a911-4a05-80c8-0c9e0d06e03a

### Obtener usuarios con filtro
GET http://localhost:3000/api/usuario/buscar?q=rosario

### Register
# @name createUsuario
POST http://localhost:3000/api/usuario/register
Content-Type: application/json

{
  "nombre":"valen",
  "apellido": "Bertucceli",
  "clave":"1234",
  "email":"valen@gmail.com",
  "direccion":"Lavalle 1120",
  "descripcion":"Soy fan de uml y un crack",
  "contacto": "3416526398",
  "horarios":"08:00 a 12:00 y 15:00 a 19:00",
  "provincia": "Ciudad Autónoma de Buenos Aires",
  "localidad": "Retiro",
  "fechaNac": "08/04/2004"
}


### Modifica una provincia (PUT - modificar recurso completo e idempotente)
@id = {{createUsuario.response.body.data.id}}
PUT http://localhost:3000/api/usuario/{{id}} 
Content-Type: application/json

{
  "nombre":"Augusto",
  "apellido": "Moratti",
  "clave":"aderf",
  "email":"augus@gmail.com",
  "descripcion":"Usuario No profesional",
  "contacto": "3416526398",
  "horarios":"08:00 a 12:00 y 15:00 a 19:00",
  "provincia": 1,
  "localidad":1,
  "profesiones": []
}

### Modificar un usuario agregando una profesion (PATCH - modificar recurso parcialmente)
PATCH http://localhost:3000/api/usuario/da9a51e9-e69d-4e51-96f3-786bba97ac31
Content-Type: application/json

{
  "horarios": "08:00 a 12:00 y 15:00 a 19:00"
}



### Eliminar una provicia (DELETE - eliminar recurso)
DELETE http://localhost:3000/api/usuario/{{id}}

### Eliminar un usuario (DELETE - eliminar recurso)
DELETE http://localhost:3000/api/usuario/bfc7a901-955b-4967-9e2e-6883143492cb

/* La extension REST Client, nos permite hacer peticiones sin la 
la necesidad del navegador, por ejemplo meter un archivo reversionado
dentro del proyecto y realizarle peticiones y controlar que funcione
todo correctamente */