GET http://localhost:3000/api/usuario

### Obtener un usuario (Con el id o cualquier otro atributo de la class)
GET http://localhost:3000/api/usuario/{{id}}

### Obtener usuarios con filtro
GET http://localhost:3000/api/usuario/buscar?q=rosario

### Register
POST http://localhost:3000/api/usuario/register
Content-Type: application/json

{
  "nombre":"Valentin",
  "apellido": "Bertucceli",
  "clave":"aderf",
  "email":"valen@gmail.com",
  "direccion":"Crespo 1288",
  "descripcion":"Usuario profesional",
  "contacto": "3416526398",
  "horarios":"08:00 a 12:00 y 15:00 a 19:00",
  "provincia": "Santa Fe",
  "localidad": "Rosario",
  "fechaNac": "08/04/2004",
  "profesiones": []
}


### Crear un nuevo usuario (POST - crear recurso)
# @name createUsuario
POST http://localhost:3000/api/usuario
Content-Type: application/json

{
  "nombre":"Valentin",
  "apellido": "Bertucceli",
  "clave":"aderf",
  "email":"valen@gmail.com",
  "descripcion":"Usuario profesional",
  "contacto": "3416526398",
  "horarios":"08:00 a 12:00 y 15:00 a 19:00",
  "provincia": 1,
  "localidad":1,
  "fechaNac": "08/04/2004",
  "profesiones": [1]
}

### Modifica una provincia (PUT - modificar recurso completo e idempotente)
@id = {{createUsuario.response.body.data.id}}
PUT http://localhost:3000/api/usuario/{{id}} 
Content-Type: application/json

{
  "nombre":"Augusto",
  "apellido": "Moratti",
  "clave":"aderf",
  "email":"augus@gmail.com",
  "descripcion":"Usuario No profesional",
  "contacto": "3416526398",
  "horarios":"08:00 a 12:00 y 15:00 a 19:00",
  "provincia": 1,
  "localidad":1,
  "profesiones": [1]
}

### Modificar una provincia (PATCH - modificar recurso parcialmente)
PATCH http://localhost:3000/api/usuario/{{id}}
Content-Type: application/json

{
  "nombre":"Marcos",
  "apellido": "Zencich",
  "descripcion":"Usuario No profesional",
  "profesiones": []
}

### Eliminar una provicia (DELETE - eliminar recurso)
DELETE http://localhost:3000/api/usuario/{{id}}


/* La extension REST Client, nos permite hacer peticiones sin la 
la necesidad del navegador, por ejemplo meter un archivo reversionado
dentro del proyecto y realizarle peticiones y controlar que funcione
todo correctamente */