GET http://localhost:3000/api/usuario

### Obtener un usuario (Con el id o cualquier otro atributo de la class)
GET http://localhost:3000/api/usuario/740966f1-41b6-4827-bcc7-bf676fc8787b

### Obtener usuarios con filtro
GET http://localhost:3000/api/usuario/buscar?q=rosario

### Register
# @name createUsuario
POST http://localhost:3000/api/usuario/register
Content-Type: application/json

{
  "nombre":"Lucas",
  "apellido": "Cossia",
  "clave":"1234",
  "email":"lucas@gmail.com",
  "direccion":"Lavalle 1120",
  "descripcion":"Soy fan de uml y un crack",
  "contacto": "3416526398",
  "horarios":"08:00 a 12:00 y 15:00 a 19:00",
  "provincia": "Santa Fe",
  "localidad": "Rosario",
  "fechaNac": "08/04/2004"
}


### Crear al admin (POST - crear recurso)
# @name createUsuario
POST http://localhost:3000/api/usuario
Content-Type: application/json

{
  "nombre":"Valentino",
  "apellido": "Bertucceli",
  "clave":"12345",
  "email":"admin@host.com",
  "direccion":"Crespo 1288",
  "descripcion":"Admin de Conectar",
  "contacto": "3416526398",
  "horarios":"",
  "provincia": "Santa Fe",
  "localidad": "Rosario",
  "fechaNac": "08/04/2004",
  "profesiones": []
}

### Modifica una provincia (PUT - modificar recurso completo e idempotente)
@id = {{createUsuario.response.body.data.id}}
PUT http://localhost:3000/api/usuario/{{id}} 
Content-Type: application/json

{
  "nombre":"Augusto",
  "apellido": "Moratti",
  "clave":"aderf",
  "email":"augus@gmail.com",
  "descripcion":"Usuario No profesional",
  "contacto": "3416526398",
  "horarios":"08:00 a 12:00 y 15:00 a 19:00",
  "provincia": 1,
  "localidad":1,
  "profesiones": [1]
}

### Modificar una provincia (PATCH - modificar recurso parcialmente)
PATCH http://localhost:3000/api/usuario/{{id}}
Content-Type: application/json

{
  "habilidades": ["mikroOrm"]
}

### Eliminar una provicia (DELETE - eliminar recurso)
DELETE http://localhost:3000/api/usuario/{{id}}

### Eliminar un usuario (DELETE - eliminar recurso)
DELETE http://localhost:3000/api/usuario/{{id}}


/* La extension REST Client, nos permite hacer peticiones sin la 
la necesidad del navegador, por ejemplo meter un archivo reversionado
dentro del proyecto y realizarle peticiones y controlar que funcione
todo correctamente */